- hosts: 127.0.0.1
  vars:
    template_git: "{{ lookup('ansible.builtin.env', 'TEMPLATE_GIT', default=Undefined)}}"
    template_path: "{{ lookup('ansible.builtin.env', 'TEMPLATE_PATH', default=Undefined)}}"
    project_git: "{{ lookup('ansible.builtin.env', 'PROJECT_GIT', default=Undefined)}}"
    project_id: "{{ lookup('ansible.builtin.env', 'PROJECT_ID', default=Undefined)}}"
  tasks:
    - fail:
      when: not template_git or not project_git
    - debug:
        msg: "Hello"
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
      register: workdir
    - name: Clone Template Repo
      ansible.builtin.git:
        repo: "{{ template_git }}"
        dest: "{{workdir.path}}/template"
    - name: Clone Project Repo
      shell: |
          gcloud source repos clone {{ project_git }} {{workdir.path}}/project --project={{ project_id }} 

    - name: Create directories
      file:
        path: "{{workdir.path}}/project/{{ item.path }}"
        state: directory
        mode: '{{ item.mode }}'
      with_community.general.filetree: "{{workdir.path}}/template/{{template_path}}"
      when: item.state == 'directory'

    - name: Template files
      template:
        src: '{{ item.src }}'
        dest: "{{workdir.path}}/project/{{ item.path }}"
        mode: '{{ item.mode }}'
      with_community.general.filetree: "{{workdir.path}}/template/{{template_path}}"
      when: item.state == 'file'

    - name: Recreate symlinks
      file:
        src: '{{ item.src }}'
        dest: "{{workdir.path}}/project/{{ item.path }}"
        state: link
        force: yes
        mode: '{{ item.mode }}'
      with_community.general.filetree: "{{workdir.path}}/template/{{template_path}}"
      when: item.state == 'link'

    - name: Commit changes #This thing should fail in cloudbuild
      shell: |
          cd  "{{workdir.path}}/project" && \
          git add . && \
          if [ $(git status --porcelain|wc -l) -gt 0 ];then git commit -am "Refresh {{ansible_date_time.iso8601}}"; fi && \
          git push origin master